/* Generated by scripts/optimize-images.mjs — do not edit by hand. */

export type ServiceImage = { blur: string; aspect: number }

export const serviceImages: Record<string, ServiceImage> = {
  "audit": {
    "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBACdASoUAA0APu1kqk4ppaQiMAgBMB2JZQAAXKzuBmdE/9xyktUQAAD+30YVdnOjWFagrYubqqUYqll/DnSILuIUCyB/t2VyolR2io4iqbGsUzMyRwAA",
    "aspect": 1.4993
  },
  "huquq": {
    "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBQCdASoUABsAPu1sqFCppiOiqA1RMB2JQBXDiLoI8k8EDDile8MSSZ8/7aYddMyDgAD+9wgKEnGOmL65xJ0cAgnrk91fvfNNF+UXpyFrLKgXjfSKX51NE+AxB86JAxmDXVWkeDbZKWczyrFNaMabN4Ddtxc1xCJQhrjfy4oRJBLZ5BmAAA==",
    "aspect": 0.7452
  },
  "kadr": {
    "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBQCdASoUAB0APu1mqk2ppaQiMAgBMB2JZwDOOB9gGs6Q7bLfTAaITyCn5wYMtSTPCgD+nl4l3iBY0/mdcQ1jandxpLsEPGqiJVgvr3u5jIk10bYwUbdIYTKXtZW9MgAqqiCblwj0DEG3tyTL0P0u+/TmRX85KP4rq341rngQAA==",
    "aspect": 0.6973
  },
  "konsaltinq": {
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAwCdASoUAA0APu1iqk4ppaQiMAgBMB2JYwCdAB0ms5xuENUC0OvAAPnkjQ3dz0SdEi9NKCCX62SY655gg0+F9xMcHJrMfDP7DGgAAAA=",
    "aspect": 1.4993
  },
  "miqrasiya": {
    "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoUAA0APu1kqU2ppaQiMAgBMB2JYwCw7BulUjSw8IxC5QAA/nz/ypTZnHkm+LsB0xe4QIcqIWXaTpPasR14svICKH5zM6bHN/s1G6vl/19Q+p9VV8AAAA==",
    "aspect": 1.4993
  },
  "muhasibat": {
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoUAA0APu1kq04ppaQiMAgBMB2JZQCw7B53zeU3snvRwAD82jVh6UYlaEKR1/6AD4Hn+/VaGxwx4MBKKiIfMfbL799qvB1lUrf9AAAA",
    "aspect": 1.4993
  },
  "qeydiyyat": {
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoUAA0APu1kqk4ppaQiMAgBMB2JQBOj+ABdSxTnRgacAADxrf9naqkNBNC0AowEJhvuDRXzcXr4BUZL4o530x9x4IaJ9te+wxD+MAAA",
    "aspect": 1.5015
  },
  "qiymetlendirme": {
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoUAA0APu1kqU2ppaQiMAgBMB2JZwAAQc15b7UFmfECEAD+8DFXcr4un/7UHfOdiSxgOg1PerRh7JDUPoN4232WkvAAAA==",
    "aspect": 1.4993
  },
  "vergi": {
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAACwBQCdASoUAB4APuFeqU2opSQiMAwBEBwJYgC1I/92sAx1Q2a9ytHr5H00eJCluQCikxtWb6AA/qmm1oKRGxa8oBipQd6jyJvMgPtui/OQT3j4l5lB8a4okCR0SwMSbJ6Dk5A9ayStGdmFuOaLrS59VAMo1x3/iuEJKxeN1dyKOB29aBhK9aEQAAA=",
    "aspect": 0.6667
  }
}

export function serviceImage(slug: string) {
  return serviceImages[slug]
}
