-- ===========================================================================
-- 004_content_refresh.sql
--
-- Generated by scripts/gen-supabase-sql.mjs — do not edit by hand.
-- Regenerate after changing src/data/content.ts.
--
-- Paste into the Supabase SQL editor and run. Safe to run more than once.
--
-- Only the Azerbaijani (az) values are written. The en/ru keys inside the
-- *_i18n columns are preserved untouched, because the source text was taken
-- verbatim from abacusaudit.az and machine-translating tax and legal wording
-- is not safe to do unreviewed.
-- ===========================================================================

BEGIN;

-- ── services: short card summary column ───────────────────────────────────
ALTER TABLE services ADD COLUMN IF NOT EXISTS summary text NOT NULL DEFAULT $$$$;
ALTER TABLE services ADD COLUMN IF NOT EXISTS summary_i18n jsonb NOT NULL DEFAULT '{}'::jsonb;

-- ── services: align the personnel slug with its public URL ────────────────
-- The site routes /xidmetler/kadr; the CMS row was still slugged hr-audit.
UPDATE services SET slug = 'kadr' WHERE slug = 'hr-audit';

-- ── services: full copy imported from abacusaudit.az ──────────────────────
UPDATE services SET
  title         = $t0$Audit xidməti$t0$,
  summary       = $t1$Mühasibat uçotunun dəqiq aparılmasının və maliyyə hesabatlarının müstəqil yoxlanılması — milli və beynəlxalq standartlara uyğun.$t1$,
  description   = $t2$<p>Audit – əmtəə istehsalı və satışı, xidmət göstərilməsi və iş görülməsi ilə məşğul olan təsərrüfat subyektlərində mühasibat uçotunun dəqiq və dürüst aparılmasının, mühasibat və maliyyə hesabatlarının müstəqil yoxlanılmasıdır.</p>
<h2>İllik maliyyə hesabatlarının auditi</h2>
<ul>
<li>Azərbaycan milli mühasibat uçotu standartlarına uyğun audit</li>
<li>Beynəlxalq maliyyə hesabatı standartlarına (BMHS) uyğun audit</li>
<li>Hesabatların tərtib edilməsi və nəzərdən keçirilməsi</li>
<li>Vergi qanunvericiliyinə uyğunluğun yoxlanılması</li>
</ul>
<h2>Xüsusi təyinatlı hesabatlar üzrə rəy</h2>
<ul>
<li>Nizamnamə kapitalının formalaşdırılması</li>
<li>Vergi bəyannamələri üzrə rəy</li>
<li>Dövlət satınalmaları müqavilələri</li>
<li>Daxili nəzarət sisteminin qiymətləndirilməsi</li>
<li>İnformasiya sistemlərinin təftişi</li>
</ul>
<h2>Mülkiyyət obyektlərinin qiymətləndirilməsi</h2>
<p>Maddi aktivlərin və intellektual mülkiyyət obyektlərinin qiymətləndirilməsi.</p>$t2$,
  icon          = $t3$shield-check$t3$,
  image_url     = $t4$/services/audit.webp$t4$,
  title_i18n       = jsonb_set(coalesce(title_i18n, '{}'::jsonb),       '{az}', to_jsonb($t5$Audit xidməti$t5$::text)),
  summary_i18n     = jsonb_set(coalesce(summary_i18n, '{}'::jsonb),     '{az}', to_jsonb($t6$Mühasibat uçotunun dəqiq aparılmasının və maliyyə hesabatlarının müstəqil yoxlanılması — milli və beynəlxalq standartlara uyğun.$t6$::text)),
  description_i18n = jsonb_set(coalesce(description_i18n, '{}'::jsonb), '{az}', to_jsonb($t7$<p>Audit – əmtəə istehsalı və satışı, xidmət göstərilməsi və iş görülməsi ilə məşğul olan təsərrüfat subyektlərində mühasibat uçotunun dəqiq və dürüst aparılmasının, mühasibat və maliyyə hesabatlarının müstəqil yoxlanılmasıdır.</p>
<h2>İllik maliyyə hesabatlarının auditi</h2>
<ul>
<li>Azərbaycan milli mühasibat uçotu standartlarına uyğun audit</li>
<li>Beynəlxalq maliyyə hesabatı standartlarına (BMHS) uyğun audit</li>
<li>Hesabatların tərtib edilməsi və nəzərdən keçirilməsi</li>
<li>Vergi qanunvericiliyinə uyğunluğun yoxlanılması</li>
</ul>
<h2>Xüsusi təyinatlı hesabatlar üzrə rəy</h2>
<ul>
<li>Nizamnamə kapitalının formalaşdırılması</li>
<li>Vergi bəyannamələri üzrə rəy</li>
<li>Dövlət satınalmaları müqavilələri</li>
<li>Daxili nəzarət sisteminin qiymətləndirilməsi</li>
<li>İnformasiya sistemlərinin təftişi</li>
</ul>
<h2>Mülkiyyət obyektlərinin qiymətləndirilməsi</h2>
<p>Maddi aktivlərin və intellektual mülkiyyət obyektlərinin qiymətləndirilməsi.</p>$t7$::text))
WHERE slug = $t8$audit$t8$;

UPDATE services SET
  title         = $t9$Vergi uçotu və vergitutma$t9$,
  summary       = $t10$Vergi uçotunun aparılması, bəyannamələrin hazırlanması, vergi yoxlamalarında müşayiət və vergi planlaşdırması.$t10$,
  description   = $t11$<p>Vergi — dövlətin və bələdiyyələrin fəaliyyətinin maliyyə təminatı məqsədi ilə vergi ödəyicilərinin mülkiyyətində olan pul vəsaitlərinin mənimsənilməsi şəklində dövlət büdcəsinə və yerli büdcələrə köçürülən məcburi, fərdi və əvəzsiz ödənişdir.</p>
<h2>Vergi auditi və müşayiət</h2>
<ul>
<li>Təşkilatın vergi qanunvericiliyinə uyğunluğunun və hesabatların düzgünlüyünün yoxlanılması</li>
<li>Vergilərin hesablanması və ödənilməsi qaydaları üzrə konsultasiya</li>
<li>Vergi yoxlamalarının müşayiəti və etirazların hazırlanması</li>
<li>Vergi mübahisələrinin həlli — şikayət və məhkəmədə təmsilçilik</li>
<li>Vergi mübahisələri ilə bağlı cinayət işlərində müdafiə</li>
</ul>
<h2>Planlaşdırma və uçot</h2>
<ul>
<li>Əməliyyatların vergi nəticələrinin qiymətləndirilməsi</li>
<li>Vergi planlaşdırması sisteminin qurulması</li>
<li>Vergi uçotunun aparılması və bəyannamələrin hazırlanması</li>
<li>Vergi uçotunun qurulması və ya bərpası</li>
<li>Fiziki şəxslərin gəlir bəyannamələri üzrə dəstək</li>
<li>Uçot siyasətinin işlənilməsi</li>
<li>Vergi mövzusunda seminar və təlimlər</li>
</ul>$t11$,
  icon          = $t12$receipt$t12$,
  image_url     = $t13$/services/vergi.webp$t13$,
  title_i18n       = jsonb_set(coalesce(title_i18n, '{}'::jsonb),       '{az}', to_jsonb($t14$Vergi uçotu və vergitutma$t14$::text)),
  summary_i18n     = jsonb_set(coalesce(summary_i18n, '{}'::jsonb),     '{az}', to_jsonb($t15$Vergi uçotunun aparılması, bəyannamələrin hazırlanması, vergi yoxlamalarında müşayiət və vergi planlaşdırması.$t15$::text)),
  description_i18n = jsonb_set(coalesce(description_i18n, '{}'::jsonb), '{az}', to_jsonb($t16$<p>Vergi — dövlətin və bələdiyyələrin fəaliyyətinin maliyyə təminatı məqsədi ilə vergi ödəyicilərinin mülkiyyətində olan pul vəsaitlərinin mənimsənilməsi şəklində dövlət büdcəsinə və yerli büdcələrə köçürülən məcburi, fərdi və əvəzsiz ödənişdir.</p>
<h2>Vergi auditi və müşayiət</h2>
<ul>
<li>Təşkilatın vergi qanunvericiliyinə uyğunluğunun və hesabatların düzgünlüyünün yoxlanılması</li>
<li>Vergilərin hesablanması və ödənilməsi qaydaları üzrə konsultasiya</li>
<li>Vergi yoxlamalarının müşayiəti və etirazların hazırlanması</li>
<li>Vergi mübahisələrinin həlli — şikayət və məhkəmədə təmsilçilik</li>
<li>Vergi mübahisələri ilə bağlı cinayət işlərində müdafiə</li>
</ul>
<h2>Planlaşdırma və uçot</h2>
<ul>
<li>Əməliyyatların vergi nəticələrinin qiymətləndirilməsi</li>
<li>Vergi planlaşdırması sisteminin qurulması</li>
<li>Vergi uçotunun aparılması və bəyannamələrin hazırlanması</li>
<li>Vergi uçotunun qurulması və ya bərpası</li>
<li>Fiziki şəxslərin gəlir bəyannamələri üzrə dəstək</li>
<li>Uçot siyasətinin işlənilməsi</li>
<li>Vergi mövzusunda seminar və təlimlər</li>
</ul>$t16$::text))
WHERE slug = $t17$vergi$t17$;

UPDATE services SET
  title         = $t18$Mühasibat uçotu$t18$,
  summary       = $t19$Müəssisənin daxili idarəetmə və maliyyə hesabatlarının hazırlanması, tam mühasibat müşayiəti və uçotun bərpası.$t19$,
  description   = $t20$<p>Mühasibat uçotu – vacib və mürəkkəb bir sistemdir. Bəzən müəssisənin gələcəyi bu sistemin düzgün və effektiv qurulmasından asılıdır. Təklif etdiyimiz xidmət müəssisənin daxili idarəetmə hesabatlarının və maliyyə hesabatlarının hazırlanması, həmçinin vergi uçotunun aparılmasıdır.</p>
<h2>Xidmətlərimiz</h2>
<ul>
<li>Mühasibat uçotunun aparılması, mühasibat (maliyyə) hesabatlarının formalaşdırılması</li>
<li>Fiziki və hüquqi şəxslərin fəaliyyətinin tam mühasibat müşayiəti</li>
<li>Rüblük və illik hesabatların müvafiq nəzarətedici orqanlara təqdim edilməsi</li>
<li>Sıfır hesabatlarının verilməsi</li>
<li>Mühasibat uçotunun qurulması və ya bərpa edilməsi</li>
<li>Müəssisənin əsas vəsaitlərinin inventarizasiyası</li>
<li>Debitor və kreditor borclarının analizi və inventarizasiyası</li>
<li>Vergiqoyma və vergi planlaşdırılması</li>
<li>Vergi yoxlamaları zamanı təşkilatın maraqlarının təmsil olunması</li>
<li>Uçot siyasətinin işlənilməsi və optimallaşdırılması</li>
<li>Müəssisənin kadrlar uçotunun aparılması</li>
</ul>$t20$,
  icon          = $t21$calculator$t21$,
  image_url     = $t22$/services/muhasibat.webp$t22$,
  title_i18n       = jsonb_set(coalesce(title_i18n, '{}'::jsonb),       '{az}', to_jsonb($t23$Mühasibat uçotu$t23$::text)),
  summary_i18n     = jsonb_set(coalesce(summary_i18n, '{}'::jsonb),     '{az}', to_jsonb($t24$Müəssisənin daxili idarəetmə və maliyyə hesabatlarının hazırlanması, tam mühasibat müşayiəti və uçotun bərpası.$t24$::text)),
  description_i18n = jsonb_set(coalesce(description_i18n, '{}'::jsonb), '{az}', to_jsonb($t25$<p>Mühasibat uçotu – vacib və mürəkkəb bir sistemdir. Bəzən müəssisənin gələcəyi bu sistemin düzgün və effektiv qurulmasından asılıdır. Təklif etdiyimiz xidmət müəssisənin daxili idarəetmə hesabatlarının və maliyyə hesabatlarının hazırlanması, həmçinin vergi uçotunun aparılmasıdır.</p>
<h2>Xidmətlərimiz</h2>
<ul>
<li>Mühasibat uçotunun aparılması, mühasibat (maliyyə) hesabatlarının formalaşdırılması</li>
<li>Fiziki və hüquqi şəxslərin fəaliyyətinin tam mühasibat müşayiəti</li>
<li>Rüblük və illik hesabatların müvafiq nəzarətedici orqanlara təqdim edilməsi</li>
<li>Sıfır hesabatlarının verilməsi</li>
<li>Mühasibat uçotunun qurulması və ya bərpa edilməsi</li>
<li>Müəssisənin əsas vəsaitlərinin inventarizasiyası</li>
<li>Debitor və kreditor borclarının analizi və inventarizasiyası</li>
<li>Vergiqoyma və vergi planlaşdırılması</li>
<li>Vergi yoxlamaları zamanı təşkilatın maraqlarının təmsil olunması</li>
<li>Uçot siyasətinin işlənilməsi və optimallaşdırılması</li>
<li>Müəssisənin kadrlar uçotunun aparılması</li>
</ul>$t25$::text))
WHERE slug = $t26$muhasibat$t26$;

UPDATE services SET
  title         = $t27$Konsaltinq$t27$,
  summary       = $t28$Mühasibat, audit, hüquq və vergi sahələrində peşəkar məsləhət — sualınızın həlli üçün günlərlə vaxt itirməyin.$t28$,
  description   = $t29$<p>Abacus Audit And Consulting MMC mühasibat, audit, hüquq, vergi və s. sahələrində konsaltinq xidmətlərini təklif edir. Hər hansı bir sual və ya problemlə üzləşdikdə, onun həlli üçün günlərlə fikirləşərək vaxt itirmək əvəzinə bizimlə əlaqə saxlayın.</p>
<h2>Konsaltinq istiqamətlərimiz</h2>
<ul>
<li>Mühasibat uçotu və maliyyə hesabatlılığı üzrə məsləhət</li>
<li>Vergi qanunvericiliyinin tətbiqi üzrə izahlar</li>
<li>Hüquqi məsələlər üzrə konsultasiya</li>
<li>İdarəetmə və biznes proseslərinin qurulması</li>
<li>Maliyyə risklərinin qiymətləndirilməsi və azaldılması</li>
</ul>
<p>Müştərinin xüsusi ehtiyaclarını və konkret iqtisadi risklərini nəzərə alan çoxfaktorlu qiymət sistemi tətbiq edirik.</p>$t29$,
  icon          = $t30$lightbulb$t30$,
  image_url     = $t31$/services/konsaltinq.webp$t31$,
  title_i18n       = jsonb_set(coalesce(title_i18n, '{}'::jsonb),       '{az}', to_jsonb($t32$Konsaltinq$t32$::text)),
  summary_i18n     = jsonb_set(coalesce(summary_i18n, '{}'::jsonb),     '{az}', to_jsonb($t33$Mühasibat, audit, hüquq və vergi sahələrində peşəkar məsləhət — sualınızın həlli üçün günlərlə vaxt itirməyin.$t33$::text)),
  description_i18n = jsonb_set(coalesce(description_i18n, '{}'::jsonb), '{az}', to_jsonb($t34$<p>Abacus Audit And Consulting MMC mühasibat, audit, hüquq, vergi və s. sahələrində konsaltinq xidmətlərini təklif edir. Hər hansı bir sual və ya problemlə üzləşdikdə, onun həlli üçün günlərlə fikirləşərək vaxt itirmək əvəzinə bizimlə əlaqə saxlayın.</p>
<h2>Konsaltinq istiqamətlərimiz</h2>
<ul>
<li>Mühasibat uçotu və maliyyə hesabatlılığı üzrə məsləhət</li>
<li>Vergi qanunvericiliyinin tətbiqi üzrə izahlar</li>
<li>Hüquqi məsələlər üzrə konsultasiya</li>
<li>İdarəetmə və biznes proseslərinin qurulması</li>
<li>Maliyyə risklərinin qiymətləndirilməsi və azaldılması</li>
</ul>
<p>Müştərinin xüsusi ehtiyaclarını və konkret iqtisadi risklərini nəzərə alan çoxfaktorlu qiymət sistemi tətbiq edirik.</p>$t34$::text))
WHERE slug = $t35$konsaltinq$t35$;

UPDATE services SET
  title         = $t36$Qiymətləndirmə$t36$,
  summary       = $t37$Biznesin, daşınmaz əmlakın, avadanlığın və qeyri-maddi aktivlərin obyektiv bazar dəyərinin müəyyən edilməsi.$t37$,
  description   = $t38$<p>Abacus Audit &amp; Consulting MMC aşağıdakı qiymətləndirmə xidmətlərini təklif edir.</p>
<h2>Qiymətləndirmə növləri</h2>
<ul>
<li><strong>Şirkət qiymətləndirilməsi</strong> — biznesin dəyərinin obyektiv və peşəkar qiymətləndirilməsini həyata keçirir, bazar dəyərini müəyyən edirik.</li>
<li><strong>Daşınmaz əmlak</strong> — yaşayış binalarının, ofislərin və sənaye obyektlərinin bazar dəyərinin təyini.</li>
<li><strong>Maşın və avadanlıq</strong> — istehsal avadanlığı, nəqliyyat vasitələri və digər maşınların dəyərinin müəyyən edilməsi.</li>
<li><strong>Qeyri-maddi aktivlər</strong> — patentlər, müəllif hüquqları, ticarət nişanları və digər qeyri-maddi aktivlərin dəyərini təyin edirik.</li>
<li><strong>BMUS üçün qiymətləndirmə</strong> — Beynəlxalq Mühasibat Uçotu Standartlarına uyğun aktivlərin dəqiq qiymətləndirilməsi.</li>
<li><strong>Sığorta risk qiymətləndirilməsi</strong> — sığorta edilmiş obyektlərin risk dərəcəsinin və potensial risklərin müəyyən edilməsi.</li>
<li><strong>Əsas vəsaitlərin yenidən qiymətləndirilməsi</strong> — cari bazar dəyərinin müəyyən edilməsi.</li>
</ul>$t38$,
  icon          = $t39$trending-up$t39$,
  image_url     = $t40$/services/qiymetlendirme.webp$t40$,
  title_i18n       = jsonb_set(coalesce(title_i18n, '{}'::jsonb),       '{az}', to_jsonb($t41$Qiymətləndirmə$t41$::text)),
  summary_i18n     = jsonb_set(coalesce(summary_i18n, '{}'::jsonb),     '{az}', to_jsonb($t42$Biznesin, daşınmaz əmlakın, avadanlığın və qeyri-maddi aktivlərin obyektiv bazar dəyərinin müəyyən edilməsi.$t42$::text)),
  description_i18n = jsonb_set(coalesce(description_i18n, '{}'::jsonb), '{az}', to_jsonb($t43$<p>Abacus Audit &amp; Consulting MMC aşağıdakı qiymətləndirmə xidmətlərini təklif edir.</p>
<h2>Qiymətləndirmə növləri</h2>
<ul>
<li><strong>Şirkət qiymətləndirilməsi</strong> — biznesin dəyərinin obyektiv və peşəkar qiymətləndirilməsini həyata keçirir, bazar dəyərini müəyyən edirik.</li>
<li><strong>Daşınmaz əmlak</strong> — yaşayış binalarının, ofislərin və sənaye obyektlərinin bazar dəyərinin təyini.</li>
<li><strong>Maşın və avadanlıq</strong> — istehsal avadanlığı, nəqliyyat vasitələri və digər maşınların dəyərinin müəyyən edilməsi.</li>
<li><strong>Qeyri-maddi aktivlər</strong> — patentlər, müəllif hüquqları, ticarət nişanları və digər qeyri-maddi aktivlərin dəyərini təyin edirik.</li>
<li><strong>BMUS üçün qiymətləndirmə</strong> — Beynəlxalq Mühasibat Uçotu Standartlarına uyğun aktivlərin dəqiq qiymətləndirilməsi.</li>
<li><strong>Sığorta risk qiymətləndirilməsi</strong> — sığorta edilmiş obyektlərin risk dərəcəsinin və potensial risklərin müəyyən edilməsi.</li>
<li><strong>Əsas vəsaitlərin yenidən qiymətləndirilməsi</strong> — cari bazar dəyərinin müəyyən edilməsi.</li>
</ul>$t43$::text))
WHERE slug = $t44$qiymetlendirme$t44$;

UPDATE services SET
  title         = $t45$Hüquqi xidmətlər$t45$,
  summary       = $t46$Vergi, əmək, valyuta, gömrük və inzibati qanunvericilik üzrə konsultasiya, məhkəmə və arbitrajda təmsilçilik.$t46$,
  description   = $t47$<p>Şirkətimiz hüquqi məsələlərin geniş spektri üzrə peşəkar dəstək göstərir.</p>
<h2>Əsas xidmətlər</h2>
<ul>
<li>Vergi, əmək, valyuta, gömrük, inzibati və cinayət qanunvericiliyi ilə əlaqədar sualların konsultasiyası</li>
<li>Məhkəmə işlərində yardım — mülki-hüquqi, vergi və inzibati məsələlər</li>
<li>Mübahisələrin məhkəməyəqədər həlli</li>
<li>Sənədlərin hazırlanması — ərizə, şikayət, xahiş</li>
<li>Arbitraj və ümumi məhkəmələrdə müştərinin müdafiəsi</li>
<li>İqtisadi sahə ilə əlaqəli cinayət işlərində vətəndaşlara yardım</li>
<li>Hüquqi şəxslərin qeydiyyatı, reorqanizasiyası və ləğvi</li>
<li>Nizamnamə sənədlərinin tərtibi</li>
<li>Layihələrin hüquqi müşayiəti</li>
</ul>
<h2>Vergi hüququ</h2>
<p>Vergi ödəyicilərinə məsləhət, vergi orqanlarında təmsilçilik və vergi hesabatlarının hazırlanması.</p>$t47$,
  icon          = $t48$scale$t48$,
  image_url     = $t49$/services/huquq.webp$t49$,
  title_i18n       = jsonb_set(coalesce(title_i18n, '{}'::jsonb),       '{az}', to_jsonb($t50$Hüquqi xidmətlər$t50$::text)),
  summary_i18n     = jsonb_set(coalesce(summary_i18n, '{}'::jsonb),     '{az}', to_jsonb($t51$Vergi, əmək, valyuta, gömrük və inzibati qanunvericilik üzrə konsultasiya, məhkəmə və arbitrajda təmsilçilik.$t51$::text)),
  description_i18n = jsonb_set(coalesce(description_i18n, '{}'::jsonb), '{az}', to_jsonb($t52$<p>Şirkətimiz hüquqi məsələlərin geniş spektri üzrə peşəkar dəstək göstərir.</p>
<h2>Əsas xidmətlər</h2>
<ul>
<li>Vergi, əmək, valyuta, gömrük, inzibati və cinayət qanunvericiliyi ilə əlaqədar sualların konsultasiyası</li>
<li>Məhkəmə işlərində yardım — mülki-hüquqi, vergi və inzibati məsələlər</li>
<li>Mübahisələrin məhkəməyəqədər həlli</li>
<li>Sənədlərin hazırlanması — ərizə, şikayət, xahiş</li>
<li>Arbitraj və ümumi məhkəmələrdə müştərinin müdafiəsi</li>
<li>İqtisadi sahə ilə əlaqəli cinayət işlərində vətəndaşlara yardım</li>
<li>Hüquqi şəxslərin qeydiyyatı, reorqanizasiyası və ləğvi</li>
<li>Nizamnamə sənədlərinin tərtibi</li>
<li>Layihələrin hüquqi müşayiəti</li>
</ul>
<h2>Vergi hüququ</h2>
<p>Vergi ödəyicilərinə məsləhət, vergi orqanlarında təmsilçilik və vergi hesabatlarının hazırlanması.</p>$t52$::text))
WHERE slug = $t53$huquq$t53$;

UPDATE services SET
  title         = $t54$Kommersiya hüquqi şəxslərin qeydiyyatı$t54$,
  summary       = $t55$Yerli və xarici investisiyalı hüquqi şəxslərin, filial və nümayəndəliklərin dövlət qeydiyyatı.$t55$,
  description   = $t56$<p>Abacus Audit And Consulting şirkətinin bu sahədə təqdim etdiyi xidmətlər aşağıdakılardan ibarətdir.</p>
<h2>Qeydiyyat növləri</h2>
<ul>
<li>Yerli investisiyalı hüquqi şəxsin fiziki şəxs tərəfindən təsisi</li>
<li>Yerli investisiyalı hüquqi şəxsin hüquqi şəxs tərəfindən təsisi</li>
<li>Xarici investisiyalı hüquqi şəxsin hüquqi şəxs tərəfindən təsisi</li>
<li>Xarici investisiyalı hüquqi şəxsin fiziki şəxs tərəfindən təsisi</li>
<li>Hüquqi şəxsin nümayəndəliyinin təsisi</li>
<li>Hüquqi şəxsin filialının təsisi</li>
</ul>
<p>Sənədlərin hazırlanmasından dövlət qeydiyyatına qədər bütün prosesi sizin adınıza aparırıq.</p>$t56$,
  icon          = $t57$building$t57$,
  image_url     = $t58$/services/qeydiyyat.webp$t58$,
  title_i18n       = jsonb_set(coalesce(title_i18n, '{}'::jsonb),       '{az}', to_jsonb($t59$Kommersiya hüquqi şəxslərin qeydiyyatı$t59$::text)),
  summary_i18n     = jsonb_set(coalesce(summary_i18n, '{}'::jsonb),     '{az}', to_jsonb($t60$Yerli və xarici investisiyalı hüquqi şəxslərin, filial və nümayəndəliklərin dövlət qeydiyyatı.$t60$::text)),
  description_i18n = jsonb_set(coalesce(description_i18n, '{}'::jsonb), '{az}', to_jsonb($t61$<p>Abacus Audit And Consulting şirkətinin bu sahədə təqdim etdiyi xidmətlər aşağıdakılardan ibarətdir.</p>
<h2>Qeydiyyat növləri</h2>
<ul>
<li>Yerli investisiyalı hüquqi şəxsin fiziki şəxs tərəfindən təsisi</li>
<li>Yerli investisiyalı hüquqi şəxsin hüquqi şəxs tərəfindən təsisi</li>
<li>Xarici investisiyalı hüquqi şəxsin hüquqi şəxs tərəfindən təsisi</li>
<li>Xarici investisiyalı hüquqi şəxsin fiziki şəxs tərəfindən təsisi</li>
<li>Hüquqi şəxsin nümayəndəliyinin təsisi</li>
<li>Hüquqi şəxsin filialının təsisi</li>
</ul>
<p>Sənədlərin hazırlanmasından dövlət qeydiyyatına qədər bütün prosesi sizin adınıza aparırıq.</p>$t61$::text))
WHERE slug = $t62$qeydiyyat$t62$;

UPDATE services SET
  title         = $t63$Kadr kargüzarlığı və HR audit$t63$,
  summary       = $t64$Kadr uçotunun qanunvericiliyə uyğun təşkili, HR sənəd şablonları, outsorsinq və kadr auditi.$t64$,
  description   = $t65$<p>Müəssisənizdə kadr sənədlərinin düzgün aparılmaması gələcəkdə ciddi hüquqi problemlərə və inzibati cərimələrə səbəb ola bilər. Kadr xidmətlərimiz məhz bu risklərin qarşısını almaq üçün nəzərdə tutulub.</p>
<h2>1. Kadr uçotunun təşkili</h2>
<ul>
<li>Kadr uçotunun AR qanunvericiliyinə uyğun təşkili</li>
<li>İcbari sığorta əməliyyatlarının icrası</li>
<li>Əməkdaşların şəxsi işlərinin yaradılması</li>
<li>Xəstəlik vərəqəsinin rəsmiləşdirilməsi</li>
<li>Əmək müqavilələrinin tərtibatı</li>
<li>Lokal normativ aktların hazırlanması</li>
<li>Ştat cədvəlinin tərtib edilməsi</li>
<li>İşçilərin EHP-də rəsmi qeydiyyata alınması</li>
</ul>
<h2>2. İnsan resursları şablonları</h2>
<p>Peşəkar mütəxəssislər tərəfindən insan resurslarının idarə edilməsi üzrə ehtiyac duyulan istənilən qaydanın və sənəd şablonlarının hazırlanması.</p>
<h2>3. Outsorsinq xidməti</h2>
<p>Peşəkar mütəxəssislərdən ibarət komandamızla outsorsinq xidməti formasında kadr kargüzarlığının həyata keçirilməsi — xərclərə qənaət edərək.</p>
<h2>4. Kadr auditi</h2>
<p>Biznesdə maliyyə və hüquqi risklərin müəyyən edilməsi, nöqsanların aşkarlanması və onların qarşısının alınması.</p>$t65$,
  icon          = $t66$users$t66$,
  image_url     = $t67$/services/kadr.webp$t67$,
  title_i18n       = jsonb_set(coalesce(title_i18n, '{}'::jsonb),       '{az}', to_jsonb($t68$Kadr kargüzarlığı və HR audit$t68$::text)),
  summary_i18n     = jsonb_set(coalesce(summary_i18n, '{}'::jsonb),     '{az}', to_jsonb($t69$Kadr uçotunun qanunvericiliyə uyğun təşkili, HR sənəd şablonları, outsorsinq və kadr auditi.$t69$::text)),
  description_i18n = jsonb_set(coalesce(description_i18n, '{}'::jsonb), '{az}', to_jsonb($t70$<p>Müəssisənizdə kadr sənədlərinin düzgün aparılmaması gələcəkdə ciddi hüquqi problemlərə və inzibati cərimələrə səbəb ola bilər. Kadr xidmətlərimiz məhz bu risklərin qarşısını almaq üçün nəzərdə tutulub.</p>
<h2>1. Kadr uçotunun təşkili</h2>
<ul>
<li>Kadr uçotunun AR qanunvericiliyinə uyğun təşkili</li>
<li>İcbari sığorta əməliyyatlarının icrası</li>
<li>Əməkdaşların şəxsi işlərinin yaradılması</li>
<li>Xəstəlik vərəqəsinin rəsmiləşdirilməsi</li>
<li>Əmək müqavilələrinin tərtibatı</li>
<li>Lokal normativ aktların hazırlanması</li>
<li>Ştat cədvəlinin tərtib edilməsi</li>
<li>İşçilərin EHP-də rəsmi qeydiyyata alınması</li>
</ul>
<h2>2. İnsan resursları şablonları</h2>
<p>Peşəkar mütəxəssislər tərəfindən insan resurslarının idarə edilməsi üzrə ehtiyac duyulan istənilən qaydanın və sənəd şablonlarının hazırlanması.</p>
<h2>3. Outsorsinq xidməti</h2>
<p>Peşəkar mütəxəssislərdən ibarət komandamızla outsorsinq xidməti formasında kadr kargüzarlığının həyata keçirilməsi — xərclərə qənaət edərək.</p>
<h2>4. Kadr auditi</h2>
<p>Biznesdə maliyyə və hüquqi risklərin müəyyən edilməsi, nöqsanların aşkarlanması və onların qarşısının alınması.</p>$t70$::text))
WHERE slug = $t71$kadr$t71$;

UPDATE services SET
  title         = $t72$Miqrasiya xidmətləri$t72$,
  summary       = $t73$Əcnəbilər üçün iş icazəsi və yaşayış icazəsinin alınması — sənədlərin hazırlanmasından təhvilinə qədər.$t73$,
  description   = $t74$<p>Azərbaycan Respublikasında əcnəbi vətəndaşların və vətəndaşlığı olmayan şəxslərin əmək fəaliyyəti ilə məşğul olması üçün iş icazəsi və yaşayış icazəsinin alınması qanunvericiliyə əsasən məcburidir.</p>
<h2>Xidmətlərimiz</h2>
<ul>
<li>İş icazəsinin alınması və müddətinin uzadılması</li>
<li>Müvəqqəti yaşayış icazəsinin rəsmiləşdirilməsi</li>
<li>Sənədlərin toplanması və hazırlanması</li>
<li>Dövlət Miqrasiya Xidmətində müşayiət</li>
<li>Qeydiyyat və uçot məsələləri üzrə konsultasiya</li>
</ul>
<p>Prosesin hər mərhələsində sizi məlumatlandırır, müddətlərə nəzarət edirik.</p>$t74$,
  icon          = $t75$globe$t75$,
  image_url     = $t76$/services/miqrasiya.webp$t76$,
  title_i18n       = jsonb_set(coalesce(title_i18n, '{}'::jsonb),       '{az}', to_jsonb($t77$Miqrasiya xidmətləri$t77$::text)),
  summary_i18n     = jsonb_set(coalesce(summary_i18n, '{}'::jsonb),     '{az}', to_jsonb($t78$Əcnəbilər üçün iş icazəsi və yaşayış icazəsinin alınması — sənədlərin hazırlanmasından təhvilinə qədər.$t78$::text)),
  description_i18n = jsonb_set(coalesce(description_i18n, '{}'::jsonb), '{az}', to_jsonb($t79$<p>Azərbaycan Respublikasında əcnəbi vətəndaşların və vətəndaşlığı olmayan şəxslərin əmək fəaliyyəti ilə məşğul olması üçün iş icazəsi və yaşayış icazəsinin alınması qanunvericiliyə əsasən məcburidir.</p>
<h2>Xidmətlərimiz</h2>
<ul>
<li>İş icazəsinin alınması və müddətinin uzadılması</li>
<li>Müvəqqəti yaşayış icazəsinin rəsmiləşdirilməsi</li>
<li>Sənədlərin toplanması və hazırlanması</li>
<li>Dövlət Miqrasiya Xidmətində müşayiət</li>
<li>Qeydiyyat və uçot məsələləri üzrə konsultasiya</li>
</ul>
<p>Prosesin hər mərhələsində sizi məlumatlandırır, müddətlərə nəzarət edirik.</p>$t79$::text))
WHERE slug = $t80$miqrasiya$t80$;

-- ── why_us_items: the five real reasons from the live site ────────────────
-- Replaces the four generic placeholders.
DELETE FROM why_us_items;
INSERT INTO why_us_items (title, description, sort_order, title_i18n, description_i18n) VALUES (
  $t81$İş təcrübəsi$t81$, $t82$Müxtəlif sənaye şirkətləri, müxtəlif xidmət sahələrində fəaliyyət göstərən şirkətlər, xarici şirkətlərin ölkəmizdə fəaliyyət göstərən filial və nümayəndəlikləri ilə işləməkdə zəngin təcrübə toplamışıq.$t82$, 1,
  jsonb_build_object('az', $t83$İş təcrübəsi$t83$::text),
  jsonb_build_object('az', $t84$Müxtəlif sənaye şirkətləri, müxtəlif xidmət sahələrində fəaliyyət göstərən şirkətlər, xarici şirkətlərin ölkəmizdə fəaliyyət göstərən filial və nümayəndəlikləri ilə işləməkdə zəngin təcrübə toplamışıq.$t84$::text)
);
INSERT INTO why_us_items (title, description, sort_order, title_i18n, description_i18n) VALUES (
  $t85$İxtisaslı heyət$t85$, $t86$Mütəmadi seminarlar, daim yenilənən metodoloji baza və qanunvericiliyin monitorinqi kadrlarımızın davamlı peşəkar inkişafını təmin edir.$t86$, 2,
  jsonb_build_object('az', $t87$İxtisaslı heyət$t87$::text),
  jsonb_build_object('az', $t88$Mütəmadi seminarlar, daim yenilənən metodoloji baza və qanunvericiliyin monitorinqi kadrlarımızın davamlı peşəkar inkişafını təmin edir.$t88$::text)
);
INSERT INTO why_us_items (title, description, sort_order, title_i18n, description_i18n) VALUES (
  $t89$Keyfiyyətə nəzarət$t89$, $t90$Xidmətlərimizin hər mərhələsində çoxsəviyyəli keyfiyyətə nəzarət sistemi tətbiq etmişik.$t90$, 3,
  jsonb_build_object('az', $t91$Keyfiyyətə nəzarət$t91$::text),
  jsonb_build_object('az', $t92$Xidmətlərimizin hər mərhələsində çoxsəviyyəli keyfiyyətə nəzarət sistemi tətbiq etmişik.$t92$::text)
);
INSERT INTO why_us_items (title, description, sort_order, title_i18n, description_i18n) VALUES (
  $t93$Kompleks yanaşma$t93$, $t94$Hərtərəfli yanaşmadan irəli gələn və müəssisənin potensialına və profilinə uyğun olaraq qurulan xidmətlər təklif edirik.$t94$, 4,
  jsonb_build_object('az', $t95$Kompleks yanaşma$t95$::text),
  jsonb_build_object('az', $t96$Hərtərəfli yanaşmadan irəli gələn və müəssisənin potensialına və profilinə uyğun olaraq qurulan xidmətlər təklif edirik.$t96$::text)
);
INSERT INTO why_us_items (title, description, sort_order, title_i18n, description_i18n) VALUES (
  $t97$Qiymət siyasəti$t97$, $t98$Müştərinin xüsusi ehtiyaclarını və konkret iqtisadi risklərini nəzərə alan çoxfaktorlu qiymət sistemi tətbiq edirik.$t98$, 5,
  jsonb_build_object('az', $t99$Qiymət siyasəti$t99$::text),
  jsonb_build_object('az', $t100$Müştərinin xüsusi ehtiyaclarını və konkret iqtisadi risklərini nəzərə alan çoxfaktorlu qiymət sistemi tətbiq edirik.$t100$::text)
);

-- ── stats ─────────────────────────────────────────────────────────────────
-- NOTE: the old third stat read "3 Ofis". Only one office address is
-- published on abacusaudit.az, so it is replaced with a verifiable figure.
-- If three offices is correct, edit this block before running.
DELETE FROM stats;
INSERT INTO stats (value, suffix, label, sort_order, label_i18n) VALUES (
  500, $t101$+$t101$, $t102$Layihə$t102$, 1, jsonb_build_object('az', $t103$Layihə$t103$::text)
);
INSERT INTO stats (value, suffix, label, sort_order, label_i18n) VALUES (
  300, $t104$+$t104$, $t105$Müştəri$t105$, 2, jsonb_build_object('az', $t106$Müştəri$t106$::text)
);
INSERT INTO stats (value, suffix, label, sort_order, label_i18n) VALUES (
  9, $t107$$t107$, $t108$Xidmət sahəsi$t108$, 3, jsonb_build_object('az', $t109$Xidmət sahəsi$t109$::text)
);
INSERT INTO stats (value, suffix, label, sort_order, label_i18n) VALUES (
  15, $t110$+$t110$, $t111$İllik təcrübə$t111$, 4, jsonb_build_object('az', $t112$İllik təcrübə$t112$::text)
);

-- ── site_settings: real contact details and social profiles ───────────────
-- The previous rows held placeholders (https://facebook.com, a wrong
-- WhatsApp number). These are the live values from abacusaudit.az.
UPDATE site_settings SET
  phone         = $t113$+994 12 480 13 41$t113$,
  email         = $t114$info@abacusaudit.az$t114$,
  address       = $t115$Bakı şəhəri, Nərimanov rayonu, Məsud Əlizadə küçəsi 138$t115$,
  facebook_url  = $t116$https://www.facebook.com/AbacusAuditConsulting$t116$,
  instagram_url = $t117$https://www.instagram.com/abacusaudit.az$t117$,
  linkedin_url  = $t118$https://az.linkedin.com/company/abacus-audit-and-consulting-llc$t118$,
  whatsapp_url  = $t119$https://wa.me/994552134939$t119$
WHERE id = 1;

-- ── faq_items: new table backing the homepage FAQ + FAQPage schema ────────
CREATE TABLE IF NOT EXISTS faq_items (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  question    text NOT NULL,
  answer      text NOT NULL,
  sort_order  int  NOT NULL DEFAULT 0,
  is_published boolean NOT NULL DEFAULT true,
  question_i18n jsonb NOT NULL DEFAULT '{}'::jsonb,
  answer_i18n   jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE faq_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read faq_items" ON faq_items;
CREATE POLICY "Public read faq_items" ON faq_items
  FOR SELECT TO public USING (is_published);
DROP POLICY IF EXISTS "Admin all faq_items" ON faq_items;
CREATE POLICY "Admin all faq_items" ON faq_items
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DELETE FROM faq_items;
INSERT INTO faq_items (question, answer, sort_order, question_i18n, answer_i18n) VALUES (
  $t120$Abacus Audit hansı lisenziya əsasında fəaliyyət göstərir?$t120$, $t121$Şirkət Azərbaycan Respublikası Auditorlar Palatasının üzvüdür — 21 iyul 2017-ci il tarixindən, AT/135 nömrəli lisenziya ilə.$t121$, 1,
  jsonb_build_object('az', $t122$Abacus Audit hansı lisenziya əsasında fəaliyyət göstərir?$t122$::text),
  jsonb_build_object('az', $t123$Şirkət Azərbaycan Respublikası Auditorlar Palatasının üzvüdür — 21 iyul 2017-ci il tarixindən, AT/135 nömrəli lisenziya ilə.$t123$::text)
);
INSERT INTO faq_items (question, answer, sort_order, question_i18n, answer_i18n) VALUES (
  $t124$Audit xidmətinin qiyməti necə müəyyən olunur?$t124$, $t125$Qiymət müəssisənin dövriyyəsi, əməliyyatların həcmi, sahəsi və iş həcmi nəzərə alınmaqla çoxfaktorlu sistem üzrə hesablanır. İlkin görüşdən sonra sizə konkret təklif təqdim edirik.$t125$, 2,
  jsonb_build_object('az', $t126$Audit xidmətinin qiyməti necə müəyyən olunur?$t126$::text),
  jsonb_build_object('az', $t127$Qiymət müəssisənin dövriyyəsi, əməliyyatların həcmi, sahəsi və iş həcmi nəzərə alınmaqla çoxfaktorlu sistem üzrə hesablanır. İlkin görüşdən sonra sizə konkret təklif təqdim edirik.$t127$::text)
);
INSERT INTO faq_items (question, answer, sort_order, question_i18n, answer_i18n) VALUES (
  $t128$Mühasibat uçotunu tam outsorsinq şəklində sizə həvalə edə bilərəmmi?$t128$, $t129$Bəli. Fiziki və hüquqi şəxslərin fəaliyyətinin tam mühasibat müşayiətini, rüblük və illik hesabatların nəzarətedici orqanlara təqdim edilməsini öz üzərimizə götürürük.$t129$, 3,
  jsonb_build_object('az', $t130$Mühasibat uçotunu tam outsorsinq şəklində sizə həvalə edə bilərəmmi?$t130$::text),
  jsonb_build_object('az', $t131$Bəli. Fiziki və hüquqi şəxslərin fəaliyyətinin tam mühasibat müşayiətini, rüblük və illik hesabatların nəzarətedici orqanlara təqdim edilməsini öz üzərimizə götürürük.$t131$::text)
);
INSERT INTO faq_items (question, answer, sort_order, question_i18n, answer_i18n) VALUES (
  $t132$Əvvəlki dövrlərin uçotu qarışıqdırsa, bərpa edə bilərsinizmi?$t132$, $t133$Bəli. Mühasibat və vergi uçotunun qurulması və ya bərpa edilməsi ayrıca xidmət kimi göstərilir. Əvvəlcə mövcud vəziyyəti təhlil edir, sonra bərpa planını təqdim edirik.$t133$, 4,
  jsonb_build_object('az', $t134$Əvvəlki dövrlərin uçotu qarışıqdırsa, bərpa edə bilərsinizmi?$t134$::text),
  jsonb_build_object('az', $t135$Bəli. Mühasibat və vergi uçotunun qurulması və ya bərpa edilməsi ayrıca xidmət kimi göstərilir. Əvvəlcə mövcud vəziyyəti təhlil edir, sonra bərpa planını təqdim edirik.$t135$::text)
);
INSERT INTO faq_items (question, answer, sort_order, question_i18n, answer_i18n) VALUES (
  $t136$Vergi yoxlaması zamanı bizi təmsil edirsinizmi?$t136$, $t137$Bəli. Vergi yoxlamalarının müşayiəti, etirazların hazırlanması, şikayət və məhkəmə mərhələsində təmsilçilik xidmətlərimizə daxildir.$t137$, 5,
  jsonb_build_object('az', $t138$Vergi yoxlaması zamanı bizi təmsil edirsinizmi?$t138$::text),
  jsonb_build_object('az', $t139$Bəli. Vergi yoxlamalarının müşayiəti, etirazların hazırlanması, şikayət və məhkəmə mərhələsində təmsilçilik xidmətlərimizə daxildir.$t139$::text)
);
INSERT INTO faq_items (question, answer, sort_order, question_i18n, answer_i18n) VALUES (
  $t140$Əcnəbi işçilər üçün iş icazəsini nə qədər müddətə alırsınız?$t140$, $t141$Müddət sənədlərin tamlığından və Dövlət Miqrasiya Xidmətinin baxış müddətindən asılıdır. Sənədlərin hazırlanmasından təhvilinə qədər bütün prosesi aparır və müddətlərə nəzarət edirik.$t141$, 6,
  jsonb_build_object('az', $t142$Əcnəbi işçilər üçün iş icazəsini nə qədər müddətə alırsınız?$t142$::text),
  jsonb_build_object('az', $t143$Müddət sənədlərin tamlığından və Dövlət Miqrasiya Xidmətinin baxış müddətindən asılıdır. Sənədlərin hazırlanmasından təhvilinə qədər bütün prosesi aparır və müddətlərə nəzarət edirik.$t143$::text)
);
INSERT INTO faq_items (question, answer, sort_order, question_i18n, answer_i18n) VALUES (
  $t144$Hansı şəhərlərdə xidmət göstərirsiniz?$t144$, $t145$Ofisimiz Bakı şəhəri, Nərimanov rayonu, Məsud Əlizadə küçəsi 138 ünvanındadır. Azərbaycanın bütün bölgələrindən olan müştərilərlə onlayn və yerində işləyirik.$t145$, 7,
  jsonb_build_object('az', $t146$Hansı şəhərlərdə xidmət göstərirsiniz?$t146$::text),
  jsonb_build_object('az', $t147$Ofisimiz Bakı şəhəri, Nərimanov rayonu, Məsud Əlizadə küçəsi 138 ünvanındadır. Azərbaycanın bütün bölgələrindən olan müştərilərlə onlayn və yerində işləyirik.$t147$::text)
);
INSERT INTO faq_items (question, answer, sort_order, question_i18n, answer_i18n) VALUES (
  $t148$İlkin konsultasiya ödənişlidirmi?$t148$, $t149$İlkin konsultasiya pulsuzdur. Bizimlə əlaqə saxlayın, ehtiyacınızı dinləyib uyğun həlli və təxmini iş həcmini izah edək.$t149$, 8,
  jsonb_build_object('az', $t150$İlkin konsultasiya ödənişlidirmi?$t150$::text),
  jsonb_build_object('az', $t151$İlkin konsultasiya pulsuzdur. Bizimlə əlaqə saxlayın, ehtiyacınızı dinləyib uyğun həlli və təxmini iş həcmini izah edək.$t151$::text)
);

COMMIT;
