/**
 * Converts the service photos imported from abacusaudit.az into web-ready
 * assets: a WebP at display width, plus a tiny blurred base64 placeholder used
 * for progressive loading.
 *
 * Run once after adding or replacing anything in public/services/_src.
 *   node scripts/optimize-images.mjs
 */

import { readdir, mkdir, readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { basename, extname, join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const srcDir = join(root, 'public/services/_src')
const outDir = join(root, 'public/services')

const WIDTH = 1200
const PLACEHOLDER_WIDTH = 20

async function main() {
  if (!existsSync(srcDir)) {
    console.error(`Missing ${srcDir} — put the original images there first.`)
    process.exit(1)
  }

  await mkdir(outDir, { recursive: true })

  const files = (await readdir(srcDir)).filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
  const placeholders = {}

  for (const file of files) {
    const slug = basename(file, extname(file))
    const input = await readFile(join(srcDir, file))

    const image = sharp(input).rotate()
    const { width = 0, height = 0 } = await image.metadata()

    await sharp(input)
      .rotate()
      .resize({ width: Math.min(WIDTH, width), withoutEnlargement: true })
      .webp({ quality: 82 })
      .toFile(join(outDir, `${slug}.webp`))

    const blur = await sharp(input)
      .rotate()
      .resize({ width: PLACEHOLDER_WIDTH })
      .blur(1.2)
      .webp({ quality: 40 })
      .toBuffer()

    placeholders[slug] = {
      blur: `data:image/webp;base64,${blur.toString('base64')}`,
      aspect: Number((width / height).toFixed(4)),
    }

    console.log(`  ${slug.padEnd(18)} ${width}x${height} -> webp`)
  }

  const ts = `/* Generated by scripts/optimize-images.mjs — do not edit by hand. */

export type ServiceImage = { blur: string; aspect: number }

export const serviceImages: Record<string, ServiceImage> = ${JSON.stringify(
    placeholders,
    null,
    2,
  )}

export function serviceImage(slug: string) {
  return serviceImages[slug]
}
`
  await writeFile(join(root, 'src/lib/serviceImages.ts'), ts, 'utf8')
  console.log(`\nWrote ${files.length} WebP files + src/lib/serviceImages.ts`)
}

await main()
