-- Fill out the 9 "Xidmətlər" (Services) pages with full content pulled from the
-- live abacusaudit.az site (each page's real copy, expanded into the bullet
-- lists actually shown there) plus a hero image per service — 8 are the
-- original site's own photos, 'huquq' (which has no dedicated photo on the
-- live site) uses a themed stock photo instead.
--
-- Run in the Supabase SQL Editor after 010_services_complete.sql.

-- ─── audit ───────────────────────────────────────────────────────────────────
UPDATE services SET
  description = $az1$<p><strong>Audit</strong> – əmtəə istehsalı və satışı, xidmət göstərilməsi və iş görülməsi ilə məşğul olan təsərrüfat subyektlərində mühasibat uçotunun dəqiq və dürüst aparılmasının, mühasibat və maliyyə hesabatlarının müstəqil yoxlanılmasıdır.</p><p>Audit dövlətin, müəssisə rəhbərliyinin və maraqlı tərəflərin qarşılıqlı marağına əsaslanır. Abacus Audit beynəlxalq səviyyəli məqsədlər güdən bizneslərə risklərin qarşısını almaqda və daxili audit yoxlamalarının aparılmasında dəstək olur.</p><p>Təklif etdiyimiz əsas audit xidmətləri:</p><ul><li>Milli və beynəlxalq standartlara uyğun illik maliyyə hesabatlarının auditi, hesabatların hazırlanması və vergi uyğunluğunun yoxlanılması</li><li>Nizamnamə kapitalının formalaşdırılması, emissiya paketləri, vergi bəyannamələri və dövlət satınalma müqavilələri üzrə xüsusi təyinatlı rəy və hesabatlar</li><li>Əmlak və qeyri-maddi aktivlərin düzgün qiymətləndirilməsinin təsdiqlənməsi</li></ul>$az1$,
  description_i18n = jsonb_build_object(
    'az', $az1b$<p><strong>Audit</strong> – əmtəə istehsalı və satışı, xidmət göstərilməsi və iş görülməsi ilə məşğul olan təsərrüfat subyektlərində mühasibat uçotunun dəqiq və dürüst aparılmasının, mühasibat və maliyyə hesabatlarının müstəqil yoxlanılmasıdır.</p><p>Audit dövlətin, müəssisə rəhbərliyinin və maraqlı tərəflərin qarşılıqlı marağına əsaslanır. Abacus Audit beynəlxalq səviyyəli məqsədlər güdən bizneslərə risklərin qarşısını almaqda və daxili audit yoxlamalarının aparılmasında dəstək olur.</p><p>Təklif etdiyimiz əsas audit xidmətləri:</p><ul><li>Milli və beynəlxalq standartlara uyğun illik maliyyə hesabatlarının auditi, hesabatların hazırlanması və vergi uyğunluğunun yoxlanılması</li><li>Nizamnamə kapitalının formalaşdırılması, emissiya paketləri, vergi bəyannamələri və dövlət satınalma müqavilələri üzrə xüsusi təyinatlı rəy və hesabatlar</li><li>Əmlak və qeyri-maddi aktivlərin düzgün qiymətləndirilməsinin təsdiqlənməsi</li></ul>$az1b$::text,
    'en', $en1$<p><strong>Audit</strong> is the independent examination of accounting records and financial statements of business entities engaged in the production and sale of goods, provision of services, and performance of work, verifying that accounting is kept accurately and honestly.</p><p>Audit rests on the mutual interest of the state, company management, and stakeholders. Abacus Audit helps businesses with international ambitions prevent risk and carries out internal audit reviews.</p><p>Our core audit services include:</p><ul><li>Annual financial statement audits under national and international standards, report preparation and tax compliance verification</li><li>Special-purpose reports and opinions on share capital formation, share issues, tax returns and public procurement contracts</li><li>Confirmation of proper valuation for property and intangible assets</li></ul>$en1$::text,
    'ru', $ru1$<p><strong>Аудит</strong> — независимая проверка бухгалтерского учёта и финансовой отчётности хозяйствующих субъектов, занимающихся производством и продажей товаров, оказанием услуг и выполнением работ, с целью подтверждения точного и добросовестного ведения учёта.</p><p>Аудит основывается на взаимном интересе государства, руководства предприятия и заинтересованных сторон. Abacus Audit помогает компаниям с международными амбициями предотвращать риски и проводит внутренние аудиторские проверки.</p><p>Наши основные аудиторские услуги:</p><ul><li>Аудит годовой финансовой отчётности по национальным и международным стандартам, подготовка отчётов и проверка налогового соответствия</li><li>Заключения и отчёты специального назначения по формированию уставного капитала, эмиссии акций, налоговым декларациям и договорам госзакупок</li><li>Подтверждение корректной оценки имущества и нематериальных активов</li></ul>$ru1$::text
  ),
  image_url = 'https://abacusaudit.az/wp-content/uploads/2024/03/G0A4984-1024x683-1.jpg'
WHERE slug = 'audit';

-- ─── vergi ───────────────────────────────────────────────────────────────────
UPDATE services SET
  description = $az2$<p><strong>Vergi</strong> – dövlətin və bələdiyyələrin fəaliyyətinin maliyyə təminatı məqsədi ilə vergi ödəyicilərinin mülkiyyətində olan pul vəsaitlərinin dövlət büdcəsinə və yerli büdcələrə köçürülməsi şəklində məcburi, fərdi, əvəzsiz ödənişdir.</p><p>Vergi uçotu vergi bazasının formalaşdırılmasını, qeydiyyatını və bölüşdürülməsini tənzimləyən sistemdir. Onun əsas funksiyası vergi öhdəliklərinin dəqiq müəyyən edilməsi üçün zəruri məlumatların toplanması, uçot registrlərində vaxtında əks etdirilməsi və hesablamaların doğruluğuna nəzarətdir.</p><p>Xidmətlərimizə daxildir:</p><ul><li>Vergi auditi – uyğunluğun yoxlanılması, vergi hesablamaları üzrə konsultasiya, vergi yoxlamalarının müşayiəti və mübahisələrdə dəstək</li><li>Vergi planlaşdırılması sisteminin qurulması</li><li>Vergi uçotunun aparılması və bəyannamələrin hazırlanıb təqdim edilməsi</li><li>Vergi mövzularında təlim və seminarların keçirilməsi</li></ul>$az2$,
  description_i18n = jsonb_build_object(
    'az', $az2b$<p><strong>Vergi</strong> – dövlətin və bələdiyyələrin fəaliyyətinin maliyyə təminatı məqsədi ilə vergi ödəyicilərinin mülkiyyətində olan pul vəsaitlərinin dövlət büdcəsinə və yerli büdcələrə köçürülməsi şəklində məcburi, fərdi, əvəzsiz ödənişdir.</p><p>Vergi uçotu vergi bazasının formalaşdırılmasını, qeydiyyatını və bölüşdürülməsini tənzimləyən sistemdir. Onun əsas funksiyası vergi öhdəliklərinin dəqiq müəyyən edilməsi üçün zəruri məlumatların toplanması, uçot registrlərində vaxtında əks etdirilməsi və hesablamaların doğruluğuna nəzarətdir.</p><p>Xidmətlərimizə daxildir:</p><ul><li>Vergi auditi – uyğunluğun yoxlanılması, vergi hesablamaları üzrə konsultasiya, vergi yoxlamalarının müşayiəti və mübahisələrdə dəstək</li><li>Vergi planlaşdırılması sisteminin qurulması</li><li>Vergi uçotunun aparılması və bəyannamələrin hazırlanıb təqdim edilməsi</li><li>Vergi mövzularında təlim və seminarların keçirilməsi</li></ul>$az2b$::text,
    'en', $en2$<p><strong>Tax</strong> is a mandatory, individual, non-refundable payment transferred from the funds of taxpayers to the state and local budgets to finance the operations of the state and municipalities.</p><p>Tax accounting is the system that governs how the tax base is formed, recorded and allocated. Its core function is gathering the data needed to determine tax liabilities accurately, recording it in registers on time, and controlling the correctness of calculations.</p><p>Our services include:</p><ul><li>Tax audit — compliance checks, advice on tax calculations, support during tax inspections and dispute assistance</li><li>Building a tax planning system</li><li>Maintaining tax records and preparing and filing tax returns</li><li>Training and seminars on tax topics</li></ul>$en2$::text,
    'ru', $ru2$<p><strong>Налог</strong> — обязательный, индивидуальный, безвозмездный платёж, перечисляемый из средств налогоплательщиков в государственный и местные бюджеты для финансового обеспечения деятельности государства и муниципалитетов.</p><p>Налоговый учёт — система, регулирующая формирование, учёт и распределение налоговой базы. Его главная функция — сбор данных, необходимых для точного определения налоговых обязательств, их своевременное отражение в регистрах и контроль правильности расчётов.</p><p>Наши услуги включают:</p><ul><li>Налоговый аудит — проверка соответствия, консультации по расчётам, сопровождение налоговых проверок и помощь при спорах</li><li>Построение системы налогового планирования</li><li>Ведение налогового учёта, подготовка и подача деклараций</li><li>Проведение обучающих семинаров по налоговым вопросам</li></ul>$ru2$::text
  ),
  image_url = 'https://abacusaudit.az/wp-content/uploads/2024/03/G0A5004-683x1024-1.jpg'
WHERE slug = 'vergi';

-- ─── konsaltinq ──────────────────────────────────────────────────────────────
UPDATE services SET
  description = $az3$<p><strong>Abacus Audit And Consulting</strong> MMC mühasibat, audit, hüquq, vergi və digər sahələrdə geniş konsaltinq xidmətləri təklif edən bir şirkətdir. Hər hansı bir sual və ya problemlə üzləşdikdə, onun həlli üçün günlərlə fikirləşərək vaxt itirmək əvəzinə bizimlə əlaqə saxlayın – bu sahədə istənilən sualı cavablandırmağa və problemi həll etməyə qadirik.</p><p>Konsaltinq xidmətlərimizə aşağıdakılar daxildir:</p><ul><li>Mühasibat uçotu və maliyyə hesabatı</li><li>Vergitutma</li><li>BMUS-un (beynəlxalq maliyyə hesabatı standartları) tətbiqi</li><li>İdarəetmə uçotu, xərclərin idarə edilməsi və məhsuldarlıq</li><li>Maliyyələşdirmə və büdcələşdirmə</li><li>Müəssisənin restrukturlaşdırılması</li><li>Korporativ idarəetmə və strateji menecment</li><li>Şirkətin təşkilati strukturunun optimallaşdırılması</li></ul>$az3$,
  description_i18n = jsonb_build_object(
    'az', $az3b$<p><strong>Abacus Audit And Consulting</strong> MMC mühasibat, audit, hüquq, vergi və digər sahələrdə geniş konsaltinq xidmətləri təklif edən bir şirkətdir. Hər hansı bir sual və ya problemlə üzləşdikdə, onun həlli üçün günlərlə fikirləşərək vaxt itirmək əvəzinə bizimlə əlaqə saxlayın – bu sahədə istənilən sualı cavablandırmağa və problemi həll etməyə qadirik.</p><p>Konsaltinq xidmətlərimizə aşağıdakılar daxildir:</p><ul><li>Mühasibat uçotu və maliyyə hesabatı</li><li>Vergitutma</li><li>BMUS-un (beynəlxalq maliyyə hesabatı standartları) tətbiqi</li><li>İdarəetmə uçotu, xərclərin idarə edilməsi və məhsuldarlıq</li><li>Maliyyələşdirmə və büdcələşdirmə</li><li>Müəssisənin restrukturlaşdırılması</li><li>Korporativ idarəetmə və strateji menecment</li><li>Şirkətin təşkilati strukturunun optimallaşdırılması</li></ul>$az3b$::text,
    'en', $en3$<p><strong>Abacus Audit and Consulting LLC</strong> offers broad consulting services in accounting, audit, law, tax and related fields. Instead of spending days searching for a solution, contact us — we can answer any question and resolve the issue in this area.</p><p>Our consulting services include:</p><ul><li>Accounting and financial reporting</li><li>Taxation</li><li>IFRS implementation</li><li>Management accounting, cost control and productivity</li><li>Financing and budgeting</li><li>Corporate restructuring</li><li>Corporate governance and strategic management</li><li>Optimising the company's organisational structure</li></ul>$en3$::text,
    'ru', $ru3$<p><strong>Abacus Audit and Consulting LLC</strong> предлагает широкий спектр консалтинговых услуг в области бухгалтерского учёта, аудита, права, налогообложения и смежных сфер. Вместо того чтобы днями искать решение, обратитесь к нам — мы готовы ответить на любой вопрос и решить проблему в этой сфере.</p><p>Наши консалтинговые услуги включают:</p><ul><li>Бухгалтерский учёт и финансовая отчётность</li><li>Налогообложение</li><li>Внедрение МСФО</li><li>Управленческий учёт, контроль затрат и повышение эффективности</li><li>Финансирование и бюджетирование</li><li>Реструктуризация предприятия</li><li>Корпоративное управление и стратегический менеджмент</li><li>Оптимизация организационной структуры компании</li></ul>$ru3$::text
  ),
  image_url = 'https://abacusaudit.az/wp-content/uploads/2026/05/3-1-1.jpg'
WHERE slug = 'konsaltinq';

-- ─── qiymetlendirme ──────────────────────────────────────────────────────────
UPDATE services SET
  description = $az4$<p><strong>Abacus Audit And Consulting</strong> mütəxəssisləri beynəlxalq standartlara uyğun, yüksək keyfiyyətli biznesin və əmlakın qiymətləndirilməsi xidmətlərini təqdim edir.</p><p>Qiymətləndirmə xidmətlərimiz:</p><ul><li>Şirkət/biznesin qiymətləndirilməsi – obyektiv bazar dəyərinin müəyyən edilməsi</li><li>Daşınmaz əmlakın qiymətləndirilməsi – yaşayış binaları, ofis və istehsalat sahələri</li><li>Avadanlıq və nəqliyyat vasitələrinin qiymətləndirilməsi</li><li>Qeyri-maddi aktivlərin (patent, müəllif hüququ, ticarət nişanları) qiymətləndirilməsi</li><li>BMHS-ə uyğun aktiv və öhdəliklərin qiymətləndirilməsi</li><li>Sığorta üçün risklərin qiymətləndirilməsi</li><li>Əsas vəsaitlərin bazar dəyərinin yenidən qiymətləndirilməsi</li></ul><p>Abacus ilə əməkdaşlıq etməklə dəqiq və peşəkar qiymətləndirmə nəticəsində daha məlumatlı maliyyə qərarları qəbul edə bilərsiniz.</p>$az4$,
  description_i18n = jsonb_build_object(
    'az', $az4b$<p><strong>Abacus Audit And Consulting</strong> mütəxəssisləri beynəlxalq standartlara uyğun, yüksək keyfiyyətli biznesin və əmlakın qiymətləndirilməsi xidmətlərini təqdim edir.</p><p>Qiymətləndirmə xidmətlərimiz:</p><ul><li>Şirkət/biznesin qiymətləndirilməsi – obyektiv bazar dəyərinin müəyyən edilməsi</li><li>Daşınmaz əmlakın qiymətləndirilməsi – yaşayış binaları, ofis və istehsalat sahələri</li><li>Avadanlıq və nəqliyyat vasitələrinin qiymətləndirilməsi</li><li>Qeyri-maddi aktivlərin (patent, müəllif hüququ, ticarət nişanları) qiymətləndirilməsi</li><li>BMHS-ə uyğun aktiv və öhdəliklərin qiymətləndirilməsi</li><li>Sığorta üçün risklərin qiymətləndirilməsi</li><li>Əsas vəsaitlərin bazar dəyərinin yenidən qiymətləndirilməsi</li></ul><p>Abacus ilə əməkdaşlıq etməklə dəqiq və peşəkar qiymətləndirmə nəticəsində daha məlumatlı maliyyə qərarları qəbul edə bilərsiniz.</p>$az4b$::text,
    'en', $en4$<p><strong>Abacus Audit and Consulting</strong> specialists deliver high-quality business and property valuation aligned with international standards.</p><p>Our valuation services:</p><ul><li>Company/business valuation — determining objective market value</li><li>Real estate valuation — residential buildings, offices and industrial premises</li><li>Equipment and vehicle valuation</li><li>Intangible asset valuation — patents, copyrights, trademarks</li><li>IFRS-compliant asset and liability valuation</li><li>Insurance risk assessment</li><li>Fixed asset revaluation at current market value</li></ul><p>Partnering with Abacus gives you an accurate, professional valuation to support better financial decisions.</p>$en4$::text,
    'ru', $ru4$<p>Специалисты <strong>Abacus Audit and Consulting</strong> предоставляют качественную оценку бизнеса и имущества в соответствии с международными стандартами.</p><p>Наши услуги по оценке:</p><ul><li>Оценка компании/бизнеса — определение объективной рыночной стоимости</li><li>Оценка недвижимости — жилые здания, офисные и производственные помещения</li><li>Оценка оборудования и транспортных средств</li><li>Оценка нематериальных активов — патентов, авторских прав, товарных знаков</li><li>Оценка активов и обязательств в соответствии с МСФО</li><li>Оценка страховых рисков</li><li>Переоценка основных средств по текущей рыночной стоимости</li></ul><p>Сотрудничество с Abacus обеспечивает точную и профессиональную оценку для более обоснованных финансовых решений.</p>$ru4$::text
  ),
  image_url = 'https://abacusaudit.az/wp-content/uploads/2024/03/shutterstock_1160497384-1024x683-1.jpg'
WHERE slug = 'qiymetlendirme';

-- ─── huquq (no dedicated photo on the live site — themed stock photo) ────────
UPDATE services SET
  description = $az5$<p><strong>Hüquqi xidmətlər</strong> – müəssisələrin fəaliyyətində yarana bilən müqavilə, əmək, korporativ və kommersiya hüququ məsələlərinin peşəkar həllidir. Abacus Audit And Consulting-in hüquq mütəxəssisləri korporativ təmsilçilik, müqavilələrin bağlanması, biznesin qurulması/ləğvi və əmək məsələləri üzrə hərtərəfli dəstək göstərir.</p><p>Əsas hüquqi xidmətlərimiz:</p><ul><li>Vergi, əmək, valyuta, gömrük, inzibati və cinayət qanunvericiliyi üzrə konsultasiya</li><li>Mülki, vergi və inzibati mübahisələrdə məhkəməyəqədər və məhkəmə mərhələsində təmsilçilik</li><li>Ərizə, şikayət və prosessual sənədlərin hazırlanması</li><li>Hüquqi şəxslərin qeydiyyatı, yenidən təşkili və ləğvi</li><li>Normativ sənədlərin və layihələrin hüquqi baxımdan müşayiəti</li></ul><p>Bundan əlavə, vergi ödəyicilərinə hüquqi məsləhət, vergi orqanları və məhkəmələrdə təmsilçilik, bəyannamələrin hazırlanması xidmətlərini də təqdim edirik.</p>$az5$,
  description_i18n = jsonb_build_object(
    'az', $az5b$<p><strong>Hüquqi xidmətlər</strong> – müəssisələrin fəaliyyətində yarana bilən müqavilə, əmək, korporativ və kommersiya hüququ məsələlərinin peşəkar həllidir. Abacus Audit And Consulting-in hüquq mütəxəssisləri korporativ təmsilçilik, müqavilələrin bağlanması, biznesin qurulması/ləğvi və əmək məsələləri üzrə hərtərəfli dəstək göstərir.</p><p>Əsas hüquqi xidmətlərimiz:</p><ul><li>Vergi, əmək, valyuta, gömrük, inzibati və cinayət qanunvericiliyi üzrə konsultasiya</li><li>Mülki, vergi və inzibati mübahisələrdə məhkəməyəqədər və məhkəmə mərhələsində təmsilçilik</li><li>Ərizə, şikayət və prosessual sənədlərin hazırlanması</li><li>Hüquqi şəxslərin qeydiyyatı, yenidən təşkili və ləğvi</li><li>Normativ sənədlərin və layihələrin hüquqi baxımdan müşayiəti</li></ul><p>Bundan əlavə, vergi ödəyicilərinə hüquqi məsləhət, vergi orqanları və məhkəmələrdə təmsilçilik, bəyannamələrin hazırlanması xidmətlərini də təqdim edirik.</p>$az5b$::text,
    'en', $en5$<p><strong>Legal services</strong> cover the professional resolution of contract, employment, corporate and commercial law matters that arise in a company's operations. Abacus Audit and Consulting's legal specialists provide comprehensive support for corporate representation, contract negotiation, business formation/dissolution and employment matters.</p><p>Our core legal services:</p><ul><li>Advice on tax, labour, currency, customs, administrative and criminal legislation</li><li>Pre-trial and court representation in civil, tax and administrative disputes</li><li>Preparation of applications, complaints and procedural documents</li><li>Registration, reorganisation and dissolution of legal entities</li><li>Legal review of regulatory documents and projects</li></ul><p>We also provide tax law advice, representation before tax authorities and courts, and preparation of tax returns.</p>$en5$::text,
    'ru', $ru5$<p><strong>Юридические услуги</strong> — профессиональное решение вопросов договорного, трудового, корпоративного и коммерческого права, возникающих в деятельности компании. Юристы Abacus Audit and Consulting оказывают всестороннюю поддержку по корпоративному представительству, заключению договоров, созданию/ликвидации бизнеса и трудовым вопросам.</p><p>Наши основные юридические услуги:</p><ul><li>Консультации по налоговому, трудовому, валютному, таможенному, административному и уголовному законодательству</li><li>Досудебное и судебное представительство по гражданским, налоговым и административным спорам</li><li>Подготовка заявлений, жалоб и процессуальных документов</li><li>Регистрация, реорганизация и ликвидация юридических лиц</li><li>Правовое сопровождение нормативных документов и проектов</li></ul><p>Мы также предоставляем консультации по налоговому праву, представительство в налоговых органах и судах, подготовку налоговых деклараций.</p>$ru5$::text
  ),
  image_url = 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80&auto=format&fit=crop'
WHERE slug = 'huquq';

-- ─── muhasibat ───────────────────────────────────────────────────────────────
UPDATE services SET
  description = $az6$<p><strong>Mühasibat uçotu</strong> – vacib və mürəkkəb bir sistemdir. Bəzən müəssisənin gələcəyi bu sistemin düzgün və effektiv qurulmasından asılıdır. Xidmətimiz müəssisənin daxili idarəetmə hesabatlarının və maliyyə hesabatlarının hazırlanmasını əhatə edir.</p><p>Mühasibat xidmətlərimizə daxildir:</p><ul><li>Hesabların aparılması və maliyyə hesabatlarının hazırlanması</li><li>Fiziki və hüquqi şəxslərin fəaliyyətinin tam mühasibat müşayiəti</li><li>Rüblük və illik hesabatların nəzarətedici orqanlara təqdim edilməsi</li><li>Aktivlərin inventarizasiyası</li><li>Debitor və kreditor öhdəliklərinin təhlili</li><li>Vergi planlaşdırılması və vergi yoxlamalarında təmsilçilik</li><li>Kadrların əmək haqqı uçotunun aparılması</li></ul>$az6$,
  description_i18n = jsonb_build_object(
    'az', $az6b$<p><strong>Mühasibat uçotu</strong> – vacib və mürəkkəb bir sistemdir. Bəzən müəssisənin gələcəyi bu sistemin düzgün və effektiv qurulmasından asılıdır. Xidmətimiz müəssisənin daxili idarəetmə hesabatlarının və maliyyə hesabatlarının hazırlanmasını əhatə edir.</p><p>Mühasibat xidmətlərimizə daxildir:</p><ul><li>Hesabların aparılması və maliyyə hesabatlarının hazırlanması</li><li>Fiziki və hüquqi şəxslərin fəaliyyətinin tam mühasibat müşayiəti</li><li>Rüblük və illik hesabatların nəzarətedici orqanlara təqdim edilməsi</li><li>Aktivlərin inventarizasiyası</li><li>Debitor və kreditor öhdəliklərinin təhlili</li><li>Vergi planlaşdırılması və vergi yoxlamalarında təmsilçilik</li><li>Kadrların əmək haqqı uçotunun aparılması</li></ul>$az6b$::text,
    'en', $en6$<p><strong>Accounting</strong> is an important and complex system — a company's future often depends on how correctly and effectively it is set up. Our service covers preparing a company's internal management reports and financial statements.</p><p>Our accounting services include:</p><ul><li>Bookkeeping and preparation of financial statements</li><li>Full accounting support for individuals and legal entities</li><li>Filing quarterly and annual reports with regulatory authorities</li><li>Asset inventory management</li><li>Analysis of receivables and payables</li><li>Tax planning and representation during tax inspections</li><li>Payroll accounting</li></ul>$en6$::text,
    'ru', $ru6$<p><strong>Бухгалтерский учёт</strong> — важная и сложная система: будущее компании часто зависит от того, насколько правильно и эффективно она выстроена. Наша услуга включает подготовку внутренней управленческой и финансовой отчётности предприятия.</p><p>Наши бухгалтерские услуги включают:</p><ul><li>Ведение учёта и подготовка финансовой отчётности</li><li>Полное бухгалтерское сопровождение физических и юридических лиц</li><li>Подача квартальной и годовой отчётности в контролирующие органы</li><li>Управление инвентаризацией активов</li><li>Анализ дебиторской и кредиторской задолженности</li><li>Налоговое планирование и представительство при налоговых проверках</li><li>Учёт заработной платы персонала</li></ul>$ru6$::text
  ),
  image_url = 'https://abacusaudit.az/wp-content/uploads/2026/05/imgi_4_G0A4845-1024x683-1.jpg'
WHERE slug = 'muhasibat';

-- ─── qeydiyyat ───────────────────────────────────────────────────────────────
UPDATE services SET
  description = $az7$<p><strong>Abacus Audit And Consulting</strong> kommersiya hüquqi şəxslərin qeydiyyatı üzrə tam sənədləşmə və dövlət orqanlarında təqdimat xidmətlərini göstərir – təsisdən dəyişikliklərin qeydə alınmasına və ləğvinə qədər.</p><p>Qeydiyyat xidmətlərimiz aşağıdakıları əhatə edir:</p><ul><li>Fiziki şəxslər tərəfindən təsis edilən daxili investisiyalı hüquqi şəxslərin qeydiyyatı</li><li>Hüquqi şəxslər tərəfindən təsis edilən daxili investisiyalı hüquqi şəxslərin qeydiyyatı</li><li>Hüquqi şəxslər tərəfindən təsis edilən xarici investisiyalı hüquqi şəxslərin qeydiyyatı</li><li>Fiziki şəxslər tərəfindən təsis edilən xarici investisiyalı hüquqi şəxslərin qeydiyyatı</li><li>Hüquqi şəxslərin nümayəndəlik ofislərinin açılması</li><li>Hüquqi şəxslərin filiallarının açılması</li></ul>$az7$,
  description_i18n = jsonb_build_object(
    'az', $az7b$<p><strong>Abacus Audit And Consulting</strong> kommersiya hüquqi şəxslərin qeydiyyatı üzrə tam sənədləşmə və dövlət orqanlarında təqdimat xidmətlərini göstərir – təsisdən dəyişikliklərin qeydə alınmasına və ləğvinə qədər.</p><p>Qeydiyyat xidmətlərimiz aşağıdakıları əhatə edir:</p><ul><li>Fiziki şəxslər tərəfindən təsis edilən daxili investisiyalı hüquqi şəxslərin qeydiyyatı</li><li>Hüquqi şəxslər tərəfindən təsis edilən daxili investisiyalı hüquqi şəxslərin qeydiyyatı</li><li>Hüquqi şəxslər tərəfindən təsis edilən xarici investisiyalı hüquqi şəxslərin qeydiyyatı</li><li>Fiziki şəxslər tərəfindən təsis edilən xarici investisiyalı hüquqi şəxslərin qeydiyyatı</li><li>Hüquqi şəxslərin nümayəndəlik ofislərinin açılması</li><li>Hüquqi şəxslərin filiallarının açılması</li></ul>$az7b$::text,
    'en', $en7$<p><strong>Abacus Audit and Consulting</strong> provides complete documentation and filing services for registering commercial legal entities with government authorities — from incorporation through recording amendments to liquidation.</p><p>Our registration services cover:</p><ul><li>Registering domestic-investment legal entities established by individuals</li><li>Registering domestic-investment legal entities established by legal entities</li><li>Registering foreign-investment legal entities established by legal entities</li><li>Registering foreign-investment legal entities established by individuals</li><li>Opening representative offices of legal entities</li><li>Opening branch offices of legal entities</li></ul>$en7$::text,
    'ru', $ru7$<p><strong>Abacus Audit and Consulting</strong> оказывает полный комплекс услуг по подготовке документов и подаче их в государственные органы для регистрации коммерческих юридических лиц — от учреждения до внесения изменений и ликвидации.</p><p>Наши услуги по регистрации включают:</p><ul><li>Регистрацию юридических лиц с внутренними инвестициями, учреждённых физическими лицами</li><li>Регистрацию юридических лиц с внутренними инвестициями, учреждённых юридическими лицами</li><li>Регистрацию юридических лиц с иностранными инвестициями, учреждённых юридическими лицами</li><li>Регистрацию юридических лиц с иностранными инвестициями, учреждённых физическими лицами</li><li>Открытие представительств юридических лиц</li><li>Открытие филиалов юридических лиц</li></ul>$ru7$::text
  ),
  image_url = 'https://abacusaudit.az/wp-content/uploads/2024/03/shutterstock_1385914955.jpg'
WHERE slug = 'qeydiyyat';

-- ─── hr-audit (public slug: kadr / "Kadr kargüzarlığı") ─────────────────────
UPDATE services SET
  description = $az8$<p>Bizim <strong>kadr kargüzarlığı</strong> xidmətimiz müəssisənizdə əmək qanunvericiliyinə uyğun kadr sənədlərinin tam və düzgün aparılmasını təmin edir.</p><p>Xidmətə daxildir:</p><ul><li>Kadr sənədlərinin Azərbaycan qanunvericiliyinə uyğun təşkili və icbari sığorta əməliyyatları</li><li>İşçilərin şəxsi işlərinin yaradılması, xəstəlik, sosial və əmək məzuniyyətlərinin sənədləşdirilməsi</li><li>Əmək kitabçalarına yazılışların aparılması və əmək müqavilələrinin hazırlanması</li><li>Müqavilələrə əlavələrin və vəzifə təlimatlarının tərtib edilməsi</li><li>Daxili əmək qaydaları, şəxsi məlumatların qorunması və əməyin mühafizəsi üzrə əsasnamələrin hazırlanması</li><li>Ştat cədvəli və məzuniyyət qrafiklərinin tərtibi, işə qəbul/köçürmə/işdən çıxarma əmrlərinin hazırlanması</li><li>İşçilərin dövlət portallarında rəsmi qeydiyyatı</li></ul><p>Həmçinin kadr idarəetməsinin outsorsinq qaydasında həvalə edilməsi və mövcud kadr sənədlərinin auditi (hüquqi və maliyyə risklərinin aşkarlanması) xidmətlərini də göstəririk.</p>$az8$,
  description_i18n = jsonb_build_object(
    'az', $az8b$<p>Bizim <strong>kadr kargüzarlığı</strong> xidmətimiz müəssisənizdə əmək qanunvericiliyinə uyğun kadr sənədlərinin tam və düzgün aparılmasını təmin edir.</p><p>Xidmətə daxildir:</p><ul><li>Kadr sənədlərinin Azərbaycan qanunvericiliyinə uyğun təşkili və icbari sığorta əməliyyatları</li><li>İşçilərin şəxsi işlərinin yaradılması, xəstəlik, sosial və əmək məzuniyyətlərinin sənədləşdirilməsi</li><li>Əmək kitabçalarına yazılışların aparılması və əmək müqavilələrinin hazırlanması</li><li>Müqavilələrə əlavələrin və vəzifə təlimatlarının tərtib edilməsi</li><li>Daxili əmək qaydaları, şəxsi məlumatların qorunması və əməyin mühafizəsi üzrə əsasnamələrin hazırlanması</li><li>Ştat cədvəli və məzuniyyət qrafiklərinin tərtibi, işə qəbul/köçürmə/işdən çıxarma əmrlərinin hazırlanması</li><li>İşçilərin dövlət portallarında rəsmi qeydiyyatı</li></ul><p>Həmçinin kadr idarəetməsinin outsorsinq qaydasında həvalə edilməsi və mövcud kadr sənədlərinin auditi (hüquqi və maliyyə risklərinin aşkarlanması) xidmətlərini də göstəririk.</p>$az8b$::text,
    'en', $en8$<p>Our <strong>HR administration</strong> service ensures your company's personnel records are kept complete and correct in line with labour legislation.</p><p>The service includes:</p><ul><li>Organising HR records per Azerbaijani law and mandatory insurance operations</li><li>Creating employee personal files and documenting sick leave, social and annual leave</li><li>Maintaining labour-book entries and drafting employment contracts</li><li>Preparing contract amendments and job descriptions</li><li>Drafting internal labour regulations, personal-data-protection and occupational-safety policies</li><li>Preparing staffing tables and leave schedules, and hiring/transfer/termination orders</li><li>Official employee registration on government portals</li></ul><p>We also offer HR management on an outsourced basis, and audits of existing HR documentation to identify legal and financial risk.</p>$en8$::text,
    'ru', $ru8$<p>Наша услуга <strong>кадрового делопроизводства</strong> обеспечивает полное и правильное ведение кадровых документов вашей компании в соответствии с трудовым законодательством.</p><p>Услуга включает:</p><ul><li>Организацию кадровых документов согласно законодательству Азербайджана и операции по обязательному страхованию</li><li>Создание личных дел сотрудников, оформление больничных, социальных и трудовых отпусков</li><li>Ведение записей в трудовых книжках и подготовку трудовых договоров</li><li>Подготовку дополнений к договорам и должностных инструкций</li><li>Разработку внутренних трудовых правил, положений о защите персональных данных и охране труда</li><li>Подготовку штатного расписания, графика отпусков, приказов о приёме, переводе и увольнении</li><li>Официальную регистрацию сотрудников на государственных порталах</li></ul><p>Мы также предлагаем аутсорсинг кадрового управления и аудит существующей кадровой документации для выявления правовых и финансовых рисков.</p>$ru8$::text
  ),
  image_url = 'https://abacusaudit.az/wp-content/uploads/2026/05/2-3.png'
WHERE slug = 'hr-audit';

-- ─── miqrasiya ───────────────────────────────────────────────────────────────
UPDATE services SET
  description = $az9$<p>Azərbaycan Respublikasında əcnəbi vətəndaşların və vətəndaşlığı olmayan şəxslərin əmək fəaliyyəti ilə məşğul olması üçün iş icazəsi və yaşama icazəsinin alınması qanunvericiliyə əsasən məcburidir.</p><p>Miqrasiya xidmətlərimiz:</p><ul><li>Müvəqqəti yaşama icazəsinin alınması və uzadılması</li><li>Daimi yaşama icazəsinin alınması və yenilənməsi</li><li>İş icazəsinin alınması və uzadılması</li></ul><p>İş icazəsi prosesi ilkin hüquqi analiz və konsultasiya, sənədlərin hazırlanması və yoxlanılması, tərcümə və zəruri hallarda notarial təsdiq, elektron müraciətin hazırlanması, Dövlət Miqrasiya Xidmətinə təqdimat və prosesin izlənilməsi mərhələlərini əhatə edir; baxılma müddəti adətən 20–30 iş günü təşkil edir.</p><p>Tələb olunan sənədlərə pasport məlumatları, əmək müqaviləsi layihəsi, peşə ixtisası sənədləri və dövlət rüsumunun ödənilməsi qəbzi daxildir. Qanunvericiliyə əməl edilməməsi fiziki şəxslər üçün 3.000–7.000 AZN, hüquqi şəxslər üçün isə 15.000–35.000 AZN məbləğində inzibati cərimə, habelə vergi və sosial ödəniş riskləri ilə nəticələnə bilər.</p>$az9$,
  description_i18n = jsonb_build_object(
    'az', $az9b$<p>Azərbaycan Respublikasında əcnəbi vətəndaşların və vətəndaşlığı olmayan şəxslərin əmək fəaliyyəti ilə məşğul olması üçün iş icazəsi və yaşama icazəsinin alınması qanunvericiliyə əsasən məcburidir.</p><p>Miqrasiya xidmətlərimiz:</p><ul><li>Müvəqqəti yaşama icazəsinin alınması və uzadılması</li><li>Daimi yaşama icazəsinin alınması və yenilənməsi</li><li>İş icazəsinin alınması və uzadılması</li></ul><p>İş icazəsi prosesi ilkin hüquqi analiz və konsultasiya, sənədlərin hazırlanması və yoxlanılması, tərcümə və zəruri hallarda notarial təsdiq, elektron müraciətin hazırlanması, Dövlət Miqrasiya Xidmətinə təqdimat və prosesin izlənilməsi mərhələlərini əhatə edir; baxılma müddəti adətən 20–30 iş günü təşkil edir.</p><p>Tələb olunan sənədlərə pasport məlumatları, əmək müqaviləsi layihəsi, peşə ixtisası sənədləri və dövlət rüsumunun ödənilməsi qəbzi daxildir. Qanunvericiliyə əməl edilməməsi fiziki şəxslər üçün 3.000–7.000 AZN, hüquqi şəxslər üçün isə 15.000–35.000 AZN məbləğində inzibati cərimə, habelə vergi və sosial ödəniş riskləri ilə nəticələnə bilər.</p>$az9b$::text,
    'en', $en9$<p>Foreign nationals and stateless persons must obtain a work permit and a residence permit to engage in employment in the Republic of Azerbaijan.</p><p>Our migration services:</p><ul><li>Obtaining and extending temporary residence permits</li><li>Obtaining and renewing permanent residence permits</li><li>Obtaining and extending work permits</li></ul><p>The work-permit process covers initial legal analysis and consultation, document preparation and review, translation and notarisation where required, preparing the electronic application, submission to the State Migration Service, and follow-up — typically taking 20–30 business days.</p><p>Required documents include passport details, a draft employment contract, professional qualification documents and proof of the state fee payment. Non-compliance can result in administrative fines of AZN 3,000–7,000 for individuals and AZN 15,000–35,000 for legal entities, plus tax and social-payment risk.</p>$en9$::text,
    'ru', $ru9$<p>Иностранные граждане и лица без гражданства обязаны получить разрешение на работу и вид на жительство для осуществления трудовой деятельности в Азербайджанской Республике.</p><p>Наши миграционные услуги:</p><ul><li>Получение и продление временного вида на жительство</li><li>Получение и продление постоянного вида на жительство</li><li>Получение и продление разрешения на работу</li></ul><p>Процесс получения разрешения на работу включает первичный юридический анализ и консультацию, подготовку и проверку документов, перевод и при необходимости нотариальное заверение, подготовку электронного заявления, подачу в Государственную миграционную службу и сопровождение процесса — как правило, 20–30 рабочих дней.</p><p>Необходимые документы включают паспортные данные, проект трудового договора, документы о квалификации и квитанцию об уплате госпошлины. Несоблюдение законодательства влечёт штрафы 3 000–7 000 манат для физических лиц и 15 000–35 000 манат для юридических лиц, а также налоговые и социальные риски.</p>$ru9$::text
  ),
  image_url = 'https://abacusaudit.az/wp-content/uploads/2026/05/G0A4921-1-scaled-2-1.png'
WHERE slug = 'miqrasiya';

-- Verify: every row should now have a non-empty description and image_url
-- SELECT slug, length(description) AS desc_len, image_url FROM services ORDER BY sort_order;
